language: c
os:
  - linux
  - osx
dist: focal
compiler:
  - gcc
  - clang
before_install:
  - .ci/before_install.sh
addons:
  apt:
    packages: 
      - cproto
      - libpcre3-dev
      - libgdbm-dev
      - doxygen
      - graphviz
      update: true
  homebrew:
    packages:
      - autoconf
      - automake
      - libtool
      - gdbm
      - pcre
      - cproto
    update: true
script: .ci/script.sh
after_success:
  - .ci/after_success.sh || travis_terminate 1
