language: c
os:
  - linux
  - osx
dist: focal
compiler:
  - gcc
  - clang
before_install:
  - .ci/dependencies.sh
addons:
  apt:
    update: true
script: .ci/build.sh
after_success:
  - .ci/generateDocumentation.sh || travis_terminate 1
