language: c
os:
  - linux
dist: focal
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -y install cproto libpcre3-dev libgdbm-dev doxygen graphviz
addons:
  apt:
    update: true
script: autoreconf -ivf && ./configure && make
after_success:
  # Generate the docs only if master, the travis_build_docs is true and we can use secure variables
  - >-
    if [[ "$TRAVIS_BRANCH" = "master" && -n "$TRAVIS_BUILD_DOCS" && "$TRAVIS_PULL_REQUEST" = "false" ]] ; then
      echo $TRAVIS_BUILD_DIR
      source .ci/setup-ssh.sh || travis_terminate 1
      .ci/generateDocumentation.sh || travis_terminate 1
    fi