name: Build Test (MacOS Latest)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: | 
        brew update
        brew install gdbm pcre
    - name: build
      run: |
        cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -S$PWD -B$PWD/build -G "Unix Makefiles"
        cmake --build $PWD/build --config Debug --target all --
        cmake --install $PWD/build
