name: Build Test (Ubuntu 20.04)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: | 
        sudo apt update -q
        sudo apt install -qy libcrypt-dev libgdbm-dev libpcre3-dev libssl-dev
    - name: make install
      run: ./install.sh
