name: Build Test (Ubuntu 20.04)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: | 
        sudo apt update -q
        sudo apt install -qy cproto libgdbm-dev
    - name: autoreconf
      run: |
        autoreconf -ivfm
        cd $GITHUB_WORKSPACE/src/libltdl/
        autoreconf -ivfm
        cd $GITHUB_WORKSPACE
        ./configure
        make distclean
    - name: make
      run: |
        ./configure --enable-warnings --enable-warnings-extra
        make
    - name: make install
      run: make install
    - name: make distclean
      run: make distclean
