name: Build Test (Ubuntu Latest)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: | 
        sudo apt update -q
        sudo apt install -qy libcrypt-dev libgdbm-dev libpcre3-dev
    - name: build
      run: | 
        cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -S$PWD -B$PWD/build -G "Unix Makefiles"
        cmake --build $PWD/build --config Debug --target all -j $(getconf _NPROCESSORS_ONLN) --
        cmake --install $PWD/build
